### ISSUE TITLE
Docker image build Error: Can't find Python executable "python"

### ISSUE THREAD

**Issue by dostiharise** [holobuilder/docker-mongodump-azure#2]
I see a few warnings and errors in the Docker image build log:

Error Log: 

    gyp ERR! configure error 
    gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

Full Log: 

    $ docker image build -t "alvyl/docker-mongodump-azure" ./

    Sending build context to Docker daemon  13.96MB
    Step 1/10 : FROM mhart/alpine-node
    latest: Pulling from mhart/alpine-node
    ff3a5c916c92: Pull complete 
    12ebf20ce693: Pull complete 
    Digest: sha256:f704ba5aa28e99649d97bae2ea77ed52d878cd2ad30f50000c96230ae61f1567
    Status: Downloaded newer image for mhart/alpine-node:latest
    ---> 700152e77738
    Step 2/10 : LABEL maintainer "philip.martzok@gmail.com"
    ---> Running in b85c5698873b
    Removing intermediate container b85c5698873b
    ---> 735402f2c0a5
    Step 3/10 : RUN npm install --global azure-cli
    ---> Running in cc4ba8adb4eb

    npm WARN deprecated github@0.1.6: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
    npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
    npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
    npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

    /usr/bin/azure -> /usr/lib/node_modules/azure-cli/bin/azure

    > fibers@1.0.15 install /usr/lib/node_modules/azure-cli/node_modules/fibers
    > node build.js || nodejs build.js

    gyp ERR! configure error 
    gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
    gyp ERR! stack     at PythonFinder.failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
    gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
    gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:16)
    gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
    gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
    gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
    gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
    gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
    gyp ERR! System Linux 4.9.87-linuxkit-aufs
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
    gyp ERR! cwd /usr/lib/node_modules/azure-cli/node_modules/fibers
    gyp ERR! node -v v10.3.0
    gyp ERR! node-gyp -v v3.6.2
    gyp ERR! not ok 
    node-gyp exited with code: 1

    Please make sure you are using a supported platform and node version. If you
    would like to compile fibers on this machine please make sure you have setup your
    build environment--
    Windows + OS X instructions here: https://github.com/nodejs/node-gyp
    Ubuntu users please run: `sudo apt-get install g++ build-essential`
    Alpine users please run: `sudo apk add python make g++`
    sh: nodejs: not found
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fibers@1.0.15 (node_modules/azure-cli/node_modules/fibers):
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fibers@1.0.15 install: `node build.js || nodejs build.js`
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT

    + azure-cli@0.10.18
    added 326 packages from 335 contributors in 561.865s
    Removing intermediate container cc4ba8adb4eb
    ---> fdfb081c3ac3
    Step 4/10 : ADD bin/mongodump /
    ---> 25cfdd1ec5c3
    Step 5/10 : RUN chmod 0755 /mongodump
    ---> Running in d686d00d857f
    Removing intermediate container d686d00d857f
    ---> abdf33e179c0
    Step 6/10 : ENV BACKUP_FILENAME backup
    ---> Running in 8b55466fc62b
    Removing intermediate container 8b55466fc62b
    ---> 166da880cbff
    Step 7/10 : ADD backup.sh /
    ---> 27283eb47f47
    Step 8/10 : RUN chmod 0755 backup.sh
    ---> Running in cf6677472832
    Removing intermediate container cf6677472832
    ---> 1e3124bc63ee
    Step 9/10 : RUN apk add --update bash
    ---> Running in fcfa2f9af358
    fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
    fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
    (1/6) Installing pkgconf (1.3.10-r0)
    (2/6) Installing ncurses-terminfo-base (6.0_p20171125-r0)
    (3/6) Installing ncurses-terminfo (6.0_p20171125-r0)
    (4/6) Installing ncurses-libs (6.0_p20171125-r0)
    (5/6) Installing readline (7.0.003-r0)
    (6/6) Installing bash (4.4.19-r1)
    Executing bash-4.4.19-r1.post-install
    Executing busybox-1.27.2-r7.trigger
    OK: 15 MiB in 19 packages
    Removing intermediate container fcfa2f9af358
    ---> 2e6e8ba47ad6
    Step 10/10 : CMD ["bash","/backup.sh"]
    ---> Running in 86d1d4480ad2
    Removing intermediate container 86d1d4480ad2
    ---> 90aa4d151526
    Successfully built 90aa4d151526
    Successfully tagged alvyl/docker-mongodump-azure:latest

**Comment by holophil** [comment]
Since we've reworked the Dockerfile (using a different base image and a different installation method for azure-cli), these errors are gone. Closing this issue.
